#!/usr/bin/env python3
"""Run the shared-module test suite outside Roblox.

Concatenates tests/stub.luau, every module under src/shared (minus the ones that
need real Roblox services), and tests/specs.luau into a single Luau chunk, then
executes it with the `luau` CLI.

    python3 tests/run_tests.py [--luau /path/to/luau]
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SHARED = ROOT / "src" / "shared"

# Net.luau talks to ReplicatedStorage and RunService; it has no logic to test.
SKIP = {"Net.luau"}

PRELUDE = """
-- Generated by tests/run_tests.py. Do not edit; edit tests/specs.luau instead.

local __cache = {}

local function __node(name, parent, loader)
\tlocal node = { Name = name, Parent = parent, __children = {}, __loader = loader }
\tsetmetatable(node, {
\t\t__index = function(self, key)
\t\t\tlocal child = rawget(self, "__children")[key]
\t\t\tif child == nil then
\t\t\t\terror(string.format("no child %q under %q", tostring(key), tostring(rawget(self, "Name"))), 2)
\t\t\tend
\t\t\treturn child
\t\tend,
\t})
\tif parent then
\t\trawget(parent, "__children")[name] = node
\tend
\treturn node
end

local function require(node)
\tlocal hit = __cache[node]
\tif hit ~= nil then
\t\treturn hit
\tend
\tlocal loader = rawget(node, "__loader")
\tif not loader then
\t\terror(string.format("%q is a folder, not a module", tostring(rawget(node, "Name"))), 2)
\tend
\tlocal result = loader(node)
\t__cache[node] = result
\treturn result
end
"""


def module_name(path: Path) -> str:
    return path.stem


def build_bundle() -> str:
    parts: list[str] = [(ROOT / "tests" / "stub.luau").read_text(), PRELUDE]

    files = sorted(p for p in SHARED.rglob("*.luau") if p.name not in SKIP)
    folders: set[str] = set()

    parts.append('\nlocal Shared = __node("Shared", nil, nil)\n')
    for path in files:
        rel = path.relative_to(SHARED).parent
        if rel != Path("."):
            key = str(rel)
            if key not in folders:
                folders.add(key)
                parts.append(
                    f'local __f_{rel.name} = __node("{rel.name}", Shared, nil)\n'
                )

    for path in files:
        rel = path.relative_to(SHARED).parent
        parent = "Shared" if rel == Path(".") else f"__f_{rel.name}"
        name = module_name(path)
        source = path.read_text()
        parts.append(
            f'\n__node("{name}", {parent}, function(script)\n{source}\nend)\n'
        )

    parts.append("\n" + (ROOT / "tests" / "specs.luau").read_text())
    return "".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--luau", default=shutil.which("luau"))
    parser.add_argument("--keep", action="store_true", help="keep the generated bundle")
    args = parser.parse_args()

    if not args.luau:
        print(
            "luau not found. Install it (https://github.com/luau-lang/luau/releases) "
            "or pass --luau /path/to/luau",
            file=sys.stderr,
        )
        return 2

    bundle = build_bundle()
    with tempfile.NamedTemporaryFile(
        "w", suffix=".luau", delete=not args.keep
    ) as handle:
        handle.write(bundle)
        handle.flush()
        if args.keep:
            print(f"bundle: {handle.name}", file=sys.stderr)
        return subprocess.run([args.luau, handle.name]).returncode


if __name__ == "__main__":
    raise SystemExit(main())
