CrateInfoWave:
  change-interval: 150
  texts:
    - "&f&lᴄ&c&lʀ&4&lᴀ&4&lᴛ&4&lᴇ &4&lɪ&4&lɴ&4&lꜰ&4&lᴏ&4&lᴍ&4&lᴀ&4&lᴛ&4&lɪ&4&lᴏ&4&lɴ"
    - "&c&lᴄ&f&lʀ&c&lᴀ&4&lᴛ&4&lᴇ &4&lɪ&4&lɴ&4&lꜰ&4&lᴏ&4&lᴍ&4&lᴀ&4&lᴛ&4&lɪ&4&lᴏ&4&lɴ"
    - "&4&lᴄ&c&lʀ&f&lᴀ&c&lᴛ&4&lᴇ &4&lɪ&4&lɴ&4&lꜰ&4&lᴏ&4&lᴍ&4&lᴀ&4&lᴛ&4&lɪ&4&lᴏ&4&lɴ"
    - "&4&lᴄ&4&lʀ&c&lᴀ&f&lᴛ&c&lᴇ &4&lɪ&4&lɴ&4&lꜰ&4&lᴏ&4&lᴍ&4&lᴀ&4&lᴛ&4&lɪ&4&lᴏ&4&lɴ"
    - "&4&lᴄ&4&lʀ&4&lᴀ&c&lᴛ&f&lᴇ &c&lɪ&4&lɴ&4&lꜰ&4&lᴏ&4&lᴍ&4&lᴀ&4&lᴛ&4&lɪ&4&lᴏ&4&lɴ"
    - "&4&lᴄ&4&lʀ&4&lᴀ&4&lᴛ&c&lᴇ &f&lɪ&c&lɴ&4&lꜰ&4&lᴏ&4&lᴍ&4&lᴀ&4&lᴛ&4&lɪ&4&lᴏ&4&lɴ"
    - "&4&lᴄ&4&lʀ&4&lᴀ&4&lᴛ&4&lᴇ &c&lɪ&f&lɴ&c&lꜰ&4&lᴏ&4&lᴍ&4&lᴀ&4&lᴛ&4&lɪ&4&lᴏ&4&lɴ"
    - "&4&lᴄ&4&lʀ&4&lᴀ&4&lᴛ&4&lᴇ &4&lɪ&c&lɴ&f&lꜰ&c&lᴏ&4&lᴍ&4&lᴀ&4&lᴛ&4&lɪ&4&lᴏ&4&lɴ"
    - "&4&lᴄ&4&lʀ&4&lᴀ&4&lᴛ&4&lᴇ &4&lɪ&4&lɴ&c&lꜰ&f&lᴏ&c&lᴍ&4&lᴀ&4&lᴛ&4&lɪ&4&lᴏ&4&lɴ"
    - "&4&lᴄ&4&lʀ&4&lᴀ&4&lᴛ&4&lᴇ &4&lɪ&4&lɴ&4&lꜰ&c&lᴏ&f&lᴍ&c&lᴀ&4&lᴛ&4&lɪ&4&lᴏ&4&lɴ"
    - "&4&lᴄ&4&lʀ&4&lᴀ&4&lᴛ&4&lᴇ &4&lɪ&4&lɴ&4&lꜰ&4&lᴏ&c&lᴍ&f&lᴀ&c&lᴛ&4&lɪ&4&lᴏ&4&lɴ"
    - "&4&lᴄ&4&lʀ&4&lᴀ&4&lᴛ&4&lᴇ &4&lɪ&4&lɴ&4&lꜰ&4&lᴏ&4&lᴍ&c&lᴀ&f&lᴛ&c&lɪ&4&lᴏ&4&lɴ"
    - "&4&lᴄ&4&lʀ&4&lᴀ&4&lᴛ&4&lᴇ &4&lɪ&4&lɴ&4&lꜰ&4&lᴏ&4&lᴍ&4&lᴀ&c&lᴛ&f&lɪ&c&lᴏ&4&lɴ"
    - "&4&lᴄ&4&lʀ&4&lᴀ&4&lᴛ&4&lᴇ &4&lɪ&4&lɴ&4&lꜰ&4&lᴏ&4&lᴍ&4&lᴀ&4&lᴛ&c&lɪ&f&lᴏ&c&lɴ"
    - "&4&lᴄ&4&lʀ&4&lᴀ&4&lᴛ&4&lᴇ &4&lɪ&4&lɴ&4&lꜰ&4&lᴏ&4&lᴍ&4&lᴀ&4&lᴛ&4&lɪ&c&lᴏ&f&lɴ"
